#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove surface
rm -f constant/triSurface/motorBike.obj.gz

rm -rf 0 > /dev/null 2>&1

cleanCase

# Reset back to static initial condition
cp -f system.static/* system/
cp system/decomposeParDict.hierarchical system/decomposeParDict
cp constant/turbulenceProperties.static constant/turbulenceProperties

#------------------------------------------------------------------------------
