#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# copy motorbike surface from resources directory
cp $FOAM_TUTORIALS/resources/geometry/motorBike.obj.gz constant/triSurface/

# Make dummy 0 directory
mkdir 0

runApplication blockMesh
cp system/decomposeParDict.hierarchical system/decomposeParDict
runApplication decomposePar

cp system/decomposeParDict.ptscotch system/decomposeParDict
runParallel snappyHexMesh -overwrite

find . -type f -iname "*level*" -exec rm {} \;

ls -d processor* | xargs -I {} rm -rf ./{}/0
ls -d processor* | xargs -I {} cp -r 0.orig ./{}/0

runParallel renumberMesh -overwrite

runParallel potentialFoam -initialiseUBCs

# run static case as input
runParallel `getApplication`

# Set-up the LES case
cp ./lesFiles/fvS* ./lesFiles/controlDict ./system/
cp ./lesFiles/turbulenceProperties ./constant/

ls -d processor* | xargs -I {} rm -rf ./{}/0
ls -d processor* | xargs -I {} mv ./{}/500 ./{}/0
ls -d processor* | xargs -I {} rm -rf ./{}/0/uniform

runParallel pisoFoam

runApplication reconstructParMesh -constant -mergeTol 1e-6

runApplication reconstructPar
